### ISSUE TITLE
Default mvn build fails

### ISSUE THREAD

**Issue by tdiesler** [rhuss/jolokia#144]
The default mvn build fails with https://github.com/rhuss/jolokia/commit/30e5992b

```
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ jolokia-mule ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /Users/tdiesler/git/jolokia/agent/mule/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/tdiesler/git/jolokia/agent/mule/src/main/java/org/jolokia/mule/MuleAgentHttpServer.java:[59,24] cannot access org.mortbay.component.AbstractLifeCycle
  class file for org.mortbay.component.AbstractLifeCycle not found
[ERROR] /Users/tdiesler/git/jolokia/agent/mule/src/main/java/org/jolokia/mule/MuleAgentHttpServer.java:[71,19] cannot find symbol
  symbol:   method start()
  location: variable server of type org.mortbay.jetty.Server
[ERROR] /Users/tdiesler/git/jolokia/agent/mule/src/main/java/org/jolokia/mule/MuleAgentHttpServer.java:[84,19] cannot find symbol
  symbol:   method stop()
  location: variable server of type org.mortbay.jetty.Server
[ERROR] /Users/tdiesler/git/jolokia/agent/mule/src/main/java/org/jolokia/mule/MuleAgentHttpServer.java:[98,22] cannot access org.mortbay.component.LifeCycle
  class file for org.mortbay.component.LifeCycle not found
[ERROR] /Users/tdiesler/git/jolokia/agent/mule/src/main/java/org/jolokia/mule/MuleAgentHttpServer.java:[107,32] cannot access javax.servlet.http.HttpServlet
  class file for javax.servlet.http.HttpServlet not found
[INFO] 5 errors 
```

with 

```
[tdiesler@localhost jolokia]$ mvn -version
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 17:22:22+0200)
Maven home: /usr/local/java/apache-maven
Java version: 1.7.0_55, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_55.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.9.3", arch: "x86_64", family: "mac"
```
